services:
  - type: web
    name: recipe-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --timeout 120 --workers 4
    envVars:
      - key: DB_HOST
        value: dpg-ct49sf0gph6c73c5vogg-a
      - key: DB_USER
        value: receipe_db_wr7o_user
      - key: DB_NAME
        value: receipe-db
      - key: DB_PASSWORD
        sync: false

  - type: postgres
    name: recipe-db
    ipAllowList: []
    plan: free 